### ISSUE TITLE
Errors on API 27

### ISSUE THREAD

**Issue by paulo-raca** [rk700/YAHFA#76]
As we talked on #74, the unit test fail on API 27.

I've confirmed it on x86 and x86_64 emulators, but I didn't test on any arm/arm64 device.

**Comment by rk700** [comment]
I compare the code of both 8.0 and 8.1:

http://androidxref.com/8.0.0_r4/xref/art/runtime/mirror/dex_cache.cc#210
http://androidxref.com/8.1.0_r33/xref/art/runtime/mirror/dex_cache.cc#216

It seems that the cached method array is no longer initialized with the helper trampoline.

Moreover, the cached method array is of type `MethodDexCacheType` instead of `ArtMethod` in 8.1, which I didn't realize before.

http://androidxref.com/8.1.0_r33/xref/art/runtime/art_method.h#743 
http://androidxref.com/8.0.0_r4/xref/art/runtime/art_method.h#704

I believe that the change in array type leads to the crash.

**Comment by rk700** [comment]
Here's a workaround which might work:

```c
    if(backupMethod) {// do method backup
        if(SDKVersion < ANDROID_O2) {
```

I've tried on x86 emulator and it works. But not yet for x86_64 and ARM devices which I don't have either.

**Comment by rk700** [comment]
This commit https://github.com/rk700/YAHFA/commit/632342d04b29f91b4cc4bf03d60e72ecf50ff860 resolves the issue finally.
